### ISSUE TITLE
[FeatureRequest]区块浏览器可展示所有区块

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-explorer#2] opened 2021-03-31 10:39 UTC
区块浏览器，blocks目前最多可查询10000块。
希望改进一下全部可查或者可搜查某指定区块，比如跳转到某页。

迁移自：

https://github.com/starcoinorg/starcoin/issues/2354

**Comment by wk3368** [comment] 2021-03-31 16:57
frontend can jump to specific page  with this [commit](https://github.com/starcoinorg/starcoin-explorer/commit/600ddef38639db8d9f1d729ccff59d1269aae4d2)

**Comment by wk3368** [comment] 2021-03-31 17:03
so far, the block list can only query the maximum 10000 blocks(500 pages),  it is caused by the [elastic default limit](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after):

`By default, you cannot use from and size to page through more than 10,000 hits. This limit is a safeguard set by the index.max_result_window index setting. If you need to page through more than 10,000 hits, use the search_after parameter instead.`

I need to fix it by changing the api with `search after`.

**Comment by wk3368** [comment] 2021-04-01 04:59
api is fixed with this [commit](https://github.com/starcoinorg/starcoin-explorer-api/commit/1628612dc6e453f7cbe95da1398e43143476e9ea)

**Closed by wk3368** 2021-04-01 04:59 UTC
Labels: help wanted
